title: Haotao Lu's Homepage
page-top-title: Haotao Lu
top-section-bg-text: Computer Science
home-subtitle: Haotao Lu&ensp;|&ensp;陆昊韬
copyright-text: '&copy; Haotao Lu 2023-2024. All Rights Reserved.'
